name: Fleeting Notes Actions
on:
  # Triggers workflow on PR but only for main branch
  pull_request:
    branches: [ main ]
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test --platform chrome
    - run: flutter build web --web-renderer html --csp 
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build appbundle --debug
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign

