name: android
on:
  # Triggers workflow on PR but only for main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'android/**'
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0-1.3.pre'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build appbundle --debug
