name: macos
on:
  # Triggers workflow on PR but only for main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'macos/**'
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.1'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build macos
