
name: test
on:
  pull_request:
    branches: [ main ]
jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.4'
        cache: true
        channel: 'stable'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y libsecret-1-dev libjsoncpp-dev libsecret-1-0
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build linux --release -v
    - run: tree build

  release-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.4'
        cache: true
        channel: 'stable'
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build windows --release -v
    - run: tree build

    

