
name: test
on:
  push:
    tags:
      - "test"
jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        cache: true
        channel: 'stable'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y libsecret-1-dev libjsoncpp-dev libsecret-1-0
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build linux --release -v
    - run: zip -r build/fn-linux.zip build/linux/x64/release/bundle 
    - name: Build AppImage using appimage-builder
      uses: docker://appimagecrafters/appimage-builder:1.1.0
      with:
        entrypoint: appimage-builder
        args: --recipe ./linux/AppImageBuilder.yml --skip-test
    - run: tree -F build 
    - uses: softprops/action-gh-release@v1 
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/fn-*.zip
          ./*.AppImage
        draft: true
        fail_on_unmatched_files: true

  release-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        cache: true
        channel: 'stable'
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build windows --release -v
    - run: dart windows/build.dart
    - run: tree build /f
    - run: tar -cvzf build/fn-windows.zip build/windows/runner/Release
    - uses: softprops/action-gh-release@v1 
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/fn-*.zip
          build/*.exe
        draft: true
        fail_on_unmatched_files: true

  release-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Checkout create-dmg repository
      uses: actions/checkout@v3
      with:
        repository: 'create-dmg/create-dmg'
        path: 'create-dmg'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        cache: true
        channel: 'stable'
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build macos --release
    - run: create-dmg/create-dmg --app-drop-link 400 30 --icon-size 128  build/fn-macos.dmg build/macos/Build/Products/Release/Fleeting\ Notes.app
    - uses: softprops/action-gh-release@v1 
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/*.dmg
        draft: true
        fail_on_unmatched_files: true
