
name: test
on:
  push:
    tags:
      - "test"
jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        cache: true
        channel: 'stable'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y libsecret-1-dev libjsoncpp-dev libsecret-1-0
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build linux --release -v
    - run: zip -r build/fn-linux.zip build/linux/x64/release/bundle 
    - name: Build AppImage using appimage-builder
      uses: docker://appimagecrafters/appimage-builder:1.1.0
      with:
        entrypoint: appimage-builder
        args: --recipe ./linux/AppImageBuilder.yml --skip-test
    - run: mv ./*.AppImage* build
    - run: tree -F build 
    - uses: softprops/action-gh-release@v1 
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/fn-*.zip
          build/*.AppImage
        draft: true
        fail_on_unmatched_files: true

  release-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        cache: true
        channel: 'stable'
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build windows --release -v
    - run: dart windows/build.dart
    - run: tree build /f
    - run: tar -cvzf build/fn-windows.zip build/windows/runner/Release
    - uses: softprops/action-gh-release@v1 
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/fn-*.zip
          build/*.exe
        draft: true
        fail_on_unmatched_files: true

  release-macos:
    # https://medium.com/flutter-community/build-sign-and-deliver-flutter-macos-desktop-applications-on-github-actions-5d9b69b0469c
    runs-on: macos-latest
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
      APPNAME: "FleetingNotesMac"
      IDENTITY_ID: 4MLDMH9QYL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          cache: true
          channel: 'stable'
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE_BASE64 }}
          MACOS_PROVISION_PROFILE_BASE64: ${{ secrets.MACOS_PROVISION_PROFILE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # import certificate and provisioning profile from secrets
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          echo $MACOS_PROVISION_PROFILE_BASE64 | base64 --decode > mac.provisionprofile

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp mac.provisionprofile ~/Library/MobileDevice/Provisioning\ Profiles

          echo "Create Keychain"
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          echo "Assign to Login Keychain"
          security default-keychain -s build.keychain
          echo "Unlock the Login Keychain"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          echo "Import certificate"
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          echo "Set Key Partition"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          echo "Find Identity"
          security find-identity
      - name: Build macOS app
        run: flutter build macos --release
      - run: ls -a $MACOS_APP_RELEASE_PATH
      - name: Sign the app
        run: /usr/bin/codesign --force --deep -s $IDENTITY_ID ./$MACOS_APP_RELEASE_PATH/$APPNAME.app
      - name: Create a dmg
        run: |
          echo "Install create-dmg"
          brew install create-dmg
          cd $MACOS_APP_RELEASE_PATH
          create-dmg \
            --volname "$APPNAME" \
            --window-pos 200 120 \
            --window-size 800 529 \
            --icon-size 130 \
            --text-size 14 \
            --icon "$APPNAME.app" 260 250 \
            --hide-extension "$APPNAME.app" \
            --app-drop-link 540 250 \
            --hdiutil-quiet \
            "$APPNAME.dmg" \
            "$APPNAME.app"
      - uses: softprops/action-gh-release@v1 
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            $MACOS_APP_RELEASE_PATH/$APPNAME.dmg
          draft: true
          fail_on_unmatched_files: true