name: web
on:
  # Triggers workflow on PR but only for main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test --platform chrome
    - run: flutter build web --web-renderer html --csp 
