
name: windows
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'windows/**'
  push:
    # for release
    tags:
      - "v*.*.*"
jobs:
  release-linux:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        cache: true
        channel: 'stable'
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build windows --release -v
    - run: dart windows/build.dart
    - run: tree build /f
    - run: tar -cvzf build/fn-windows.zip build/windows/runner/Release
    - uses: softprops/action-gh-release@v1 
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/fn-*.zip
          build/*.exe
        draft: true
        fail_on_unmatched_files: true
